# Generated by Django 3.2 on 2021-05-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_sait', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='comment',
            field=models.CharField(default='', max_length=250, verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
