# Generated by Django 3.2 on 2021-06-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_sait', '0002_marks_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Комментарий'),
        ),
    ]
